name: Trading Bot

on:
  schedule:
    - cron: "0 9 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Create folders
        run: |
          mkdir -p data/cache

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python src/main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: data/
